#--------------------------------------------------------------------
# This action/workflow checks for broken links on every first of the month
# and creates an issue for the same if found any.
# It can also be manually run from GitHub action center of the repository.
# It uses markdown template to create the issue located here
# .github/ISSUE_TEMPLATE/check-broken-links.md
#
# Sources Used
# https://crontab.guru/#0_1_1_*_*
# https://github.com/lycheeverse/lychee-action
# https://github.com/marketplace/actions/create-an-issue
#----------------------------------------------------------------------


name: Check Broken Links

on:
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:

env:
  URL: https://open-horizon.github.io/
  ISSUE_TEMPLATE: ".github/ISSUE_TEMPLATE/check-broken-links.md"

jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Check links with Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress '${{ env.URL }}'
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create issue for broken links
        uses: JasonEtco/create-an-issue@v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}?check_suite_focus=true
        with:
          filename: ${{ env.ISSUE_TEMPLATE }}
        if: failure()
